name: Build and Publish Frontend
on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files in directory
        run: ls

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install dependencies
        working-directory: frontend/WeDoHr
        run: npm ci

      - name: Build Angular project
        working-directory: frontend/WeDoHr
        run: npm run build

      - name: Publish artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: app-artifacts
          path: frontend/WeDoHr/dist/

      
